from operator import add
from typing import Annotated, Any

from typing_extensions import TypedDict

from company_ai.models.agent import AgentTask


class DeepAgentState(TypedDict, total=False):

    # Original user request
    goal: str

    # Tasks generated by planner
    tasks: list[AgentTask]

    # One result is returned by every worker.
    #
    # LangGraph combines parallel updates using
    # operator.add.
    worker_results: Annotated[
        list[dict[str, Any]],
        add,
    ]

    # Final reducer output
    final_result: Any

    # Runtime iteration
    iteration: int